### ISSUE TITLE
Server should have option to run async

### ISSUE THREAD

**Issue by roytruelove** [dignifiedquire/grunt-testacular#2]
(first off thanks for writing this..)

Server should have option to run async to allow grunt's watcher to handle the watch.

Testacular's autoWatch is useful outside of Grunt, but inside of grunt I already have a watcher that's compiling my coffeescript, etc.  As part of that watch I can also have it call testacularRun.  However, there's no way to start the server before the watch - the server blocks and the watch task is never called.

**Comment by dignifiedquire** [comment]
Done and done. I've modeled it know after the upcoming `grunt-contrib-server` task and it defaults now to just starting up only if you pass `keepalive:true` it will stay alive on its own. 
I've published it already on npm as `0.2.0`.

**Comment by roytruelove** [comment]
Beautiful!  I'll give it a shot now and toss out my 1/2 done pull request :)
