### ISSUE TITLE
singleRun not working

### ISSUE THREAD

**Issue by geddski** [dignifiedquire/grunt-testacular#6]
Hey there. With this config:

``` js
testacularServer: {
    unitCI: {
        options: {
          singleRun: true
        },
        configFile: 'config/testacular.conf.js'
      }
}
```

`$ grunt testacularServer` fires up Chrome but doesn't run any tests or quit Chrome as expected. Output:

`
info: Testacular server started at http://localhost:9876/
info (launcher): Starting browser Chrome
info: To run via this server, use "testacular run --runner-port 9101"
` 

If I set the keepalive option to true then my tests run fine, but I'm after the CI mode. Thanks!

**Comment by geddski** [comment]
Also, if I run testacular manually like so:

`node_modules/grunt-testacular/node_modules/testacular/bin/testacular start config/testacular.conf.js --single-run` Chrome opens, tests pass, Chrome quits as expected.

**Comment by geddski** [comment]
Hey, so I noticed that nothing in the `options` even gets picked up by testacular, it has to be on `this.data` itself. Not sure if that's something new in testacular or what.

**Comment by dignifiedquire** [comment]
I'll look into it. What version of testacular and grunt-testacular are you using?

**Comment by geddski** [comment]
0.3.0 & 0.5.7

**Comment by dignifiedquire** [comment]
Can you try adding keepalive: true to the options?

**Comment by geddski** [comment]
Tried that, didn't work as expected. In the end I decided to just make my own grunt plugin with a few improvements (IMO): 
- JS instead of CoffeeScript (fits better in the rest of my stack)
- combined testacularRun and testacularServer into a single grunt task
- removed the early exit outside of the testacular callback

Here's my repo: https://github.com/OpenWebStack/gruntacular

If you'd like to collaborate I'd be happy to maintain this effort going forward, or our projects can live happily side by side. We're talking about like 17 LOC. 

Either way, thanks for your help.

**Comment by dignifiedquire** [comment]
No problem, I think it should be enough to have one repository. I really like the approach to took to combine the functionality into one task. I have been super busy with the next stable release of Testacular and didn't have the time to keep things here up to date.
Imo the name `grunt-testacular`  is easier to find for people so I think we should use that. If you want I can just take your code and publish it as the new `grunt-testacular`  and add you as a collaborator on this repo

**Comment by geddski** [comment]
@Dignifiedquire that's kind of you. On second thought though, it might be good to have a couple of implementations, like there are for grunt+mocha and others. We can bounce ideas off each other and maybe down the road merge into a grunt-contrib plugin. Keep up the great work on testacular, you guys are doing a phenomenal job!
